- name: Install docker
  gather_facts: No
  any_errors_fatal: true
  hosts: my_ansible_react
  become: true
  vars_files:
    - secret.yml
  tasks:
    - name: upgrade all packages
      ansible.builtin.yum: 
        name: '*'
        state: latest
    # we may need to uninstall any existing docker files from the centos repo first. 
    - name: Remove docker if installed from CentOS repo
      ansible.builtin.yum:
        name:
          - docker
          - docker-client
          - docker-client-latest
          - docker-common
          - docker-latest
          - docker-latest-logrotate
          - docker-logrotate
          - docker-engine
        state: removed

  # # yum-utils is a collection of tools and programs for managing yum repositories, installing debug packages, source packages, extended information from repositories and administration.
    - name: Install yum utils
      ansible.builtin.yum:
        name: "yum-utils"
        state: latest

  # # set up the repository (`yum_repository` modul can be used)
    - name: Add Docker repo
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    - name: Install Docker
      ansible.builtin.package:
        name: docker-ce
        state: latest

    - name: Add user ec2-user to docker group
      ansible.builtin.user:
        name: ec2-user
        groups: docker
        append: yes

    - name: Start Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: copy files to the node node
      ansible.builtin.copy:
        src: /home/ec2-user/ansible-project/react/
        dest: /home/ec2-user/react

# Remove the container if it exists
    - name: remove cla_react container
      community.docker.docker_container:
        name: cla_react
        state: absent
        force_kill: true

# Remove the image if it exists
    - name: remove clarusway/react image
      community.docker.docker_image:
        name: clarusway/react
        state: absent

    - name: build container image
      community.docker.docker_image:
        name: clarusway/react
        build:
          path: /home/ec2-user/react
        source: build
        state: present
      register: image_info

    - name: print the image info
      ansible.builtin.debug:
        var: image_info

    - name: Launch react docker container
      community.docker.docker_container:
        name: cla_react
        image: clarusway/react
        state: started
        ports:
        - "3000:3000"
      register: container_info
    
    - name: print the container info
      ansible.builtin.debug:
        var: container_info